name: masamune_agora
description: >-
  Plugin module for agora.io of Masamune framework.
  RTC and RTM available.
version: 0.4.0+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_agora

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Permission  
  permission_handler: ^5.0.0
  # Agora.io
  agora_rtc_engine: ^1.0.12
  agora_rtm: ^0.9.11
  # Masamune
  masamune_core: ^0.4.0
  masamune_mobile: ^0.4.0
  masamune_flutter: ^0.4.0
  masamune_localize: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0
  
# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_mobile:
#     path: ../masamune_mobile/
#   masamune_localize:
#     path: ../masamune_localize/
#   masamune_flutter:
#     path: ../masamune_flutter/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
